% Script Setup_ADCP_tools

%% Clean-up work space
clear all %#ok<CLSCR>
close all

%% keep key-directory available to all functions
global key_dir root_dir

%% define the root directory
root_dir = 'D:\MPhill\Modify_codes';

%% Set-up directories for the operating environment
key_dir = [root_dir filesep 'key']; % define location of parameter key files

%% Set-up the path to the Matlab scripts and functions
savepath([root_dir 'pathdef' datestr(now,'yymmdd') '.m']);
restoredefaultpath;
addpath( ...
    [root_dir  filesep 'client'], ...
    [root_dir  filesep 'core'], ...
    [root_dir  filesep 'wave'], ...
    [root_dir  filesep 'current'], ...
    [root_dir  filesep 'turbulence'], ...
    [root_dir  filesep 'utility'], ...
    [root_dir  filesep 'external'] ...
);
%     [root_dir  filesep 'core\ensembles'], ...
%     [root_dir  filesep 'core\packets'], ...

